version: '3'

services:

  postgres:
    image: sameersbn/postgresql:10-1
    restart: always
    environment:
      DB_NAME: pawandfeet
      DB_USER: postgres
      DB_PASS: pawandfeet
      PG_PASSWORD: pawandfeet
    ports:
      - 5432:5432